#include <fstream>

#include "./PolyDiM/gedim/GeDiM/src/Mesh/VtkMeshInterface.hpp"
#include "./PolyDiM/gedim/GeDiM/src/Mesh/MeshDAOImporterFromCsv.hpp"
#include "./PolyDiM/gedim/GeDiM/src/Mesh/ConformerMeshSegment.hpp"
#include "./PolyDiM/gedim/GeDiM/src/Mesh/MeshMatricesDAO.hpp"
#include "./PolyDiM/gedim/GeDiM/src/Mesh/VoroInterface.hpp"
#include "./PolyDiM/gedim/GeDiM/src/Mesh/MeshUtilities.hpp"
#include "./PolyDiM/gedim/GeDiM/src/Mesh/IntersectorMesh3DSegment.hpp"
#include "./PolyDiM/gedim/GeDiM/src/Mesh/MeshFromCsvUtilities.hpp"
#include "./PolyDiM/gedim/GeDiM/src/Mesh/ConformerMeshPolygon.hpp"
#include "./PolyDiM/gedim/GeDiM/src/Mesh/ObjectFileFormatInterface.hpp"
#include "./PolyDiM/gedim/GeDiM/src/Mesh/SphereMeshUtilities.hpp"
#include "./PolyDiM/gedim/GeDiM/src/Mesh/TriangleInterface.hpp"
#include "./PolyDiM/gedim/GeDiM/src/Mesh/UnionMeshSegment.hpp"
#include "./PolyDiM/gedim/GeDiM/src/Mesh/OpenVolumeMeshInterface.hpp"
#include "./PolyDiM/gedim/GeDiM/src/Mesh/MeshDAOExporterToCsv.hpp"
#include "./PolyDiM/gedim/GeDiM/src/Mesh/TetgenInterface.hpp"
#include "./PolyDiM/gedim/GeDiM/src/Mesh/MeshMatrices.hpp"
#include "./PolyDiM/gedim/GeDiM/src/Mesh/RefinementUtilities.hpp"
#include "./PolyDiM/gedim/GeDiM/src/Mesh/IntersectorMesh2DSegment.hpp"
#include "./PolyDiM/gedim/GeDiM/src/Mesh/PlatonicSolid.hpp"
#include "./PolyDiM/gedim/GeDiM/src/Mesh/IMeshDAO.hpp"
#include "./PolyDiM/gedim/GeDiM/src/Mesh/ConformMeshUtilities.hpp"

// #include "./PolyDiM/gedim/GeDiM/src/IO/TimeUtilities.hpp"
#include "./PolyDiM/gedim/GeDiM/src/IO/IOUtilities.hpp"
#include "./PolyDiM/gedim/GeDiM/src/IO/IOStream.hpp"
// #include "./PolyDiM/gedim/GeDiM/src/IO/UCDUtilities.hpp"
// #include "./PolyDiM/gedim/GeDiM/src/IO/VTKUtilities.hpp"
// #include "./PolyDiM/gedim/GeDiM/src/IO/Configurations.hpp"
// #include "./PolyDiM/gedim/GeDiM/src/IO/ImportExportUtilities.hpp"
// #include "./PolyDiM/gedim/GeDiM/src/IO/FileTextReader.hpp"
// #include "./PolyDiM/gedim/GeDiM/src/IO/IFileTextReader.hpp"
// #include "./PolyDiM/gedim/GeDiM/src/IO/ConfigurationPropertySupportedTypes.hpp"
#include "./PolyDiM/gedim/GeDiM/src/IO/StringsUtilities.hpp"

#include "./PolyDiM/gedim/GeDiM/src/Quadrature/Quadrature_Gauss2D_Triangle.hpp"
#include "./PolyDiM/gedim/GeDiM/src/Quadrature/Quadrature_Gauss2D_Square.hpp"
#include "./PolyDiM/gedim/GeDiM/src/Quadrature/Quadrature_Gauss3D_Hexahedron.hpp"
#include "./PolyDiM/gedim/GeDiM/src/Quadrature/Quadrature_GaussLobatto1D.hpp"
#include "./PolyDiM/gedim/GeDiM/src/Quadrature/Quadrature_Gauss1D.hpp"
#include "./PolyDiM/gedim/GeDiM/src/Quadrature/QuadratureData.hpp"
#include "./PolyDiM/gedim/GeDiM/src/Quadrature/Quadrature_Gauss3D_Tetrahedron_PositiveWeights.hpp"
#include "./PolyDiM/gedim/GeDiM/src/Quadrature/Quadrature_Gauss3D_Tetrahedron.hpp"

// #include "./PolyDiM/gedim/GeDiM/src/Common/CommonUtilities.hpp"

// #include "./PolyDiM/gedim/GeDiM/src/MpiTools/MpiParallelEnvironment.hpp"
// #include "./PolyDiM/gedim/GeDiM/src/MpiTools/IMpiProcess.hpp"
// #include "./PolyDiM/gedim/GeDiM/src/MpiTools/MetisUtilities.hpp"
// #include "./PolyDiM/gedim/GeDiM/src/MpiTools/MpiProcess.hpp"
// #include "./PolyDiM/gedim/GeDiM/src/MpiTools/GraphUtilities.hpp"

#include "./PolyDiM/gedim/GeDiM/src/Geometry/MapTetrahedron.hpp"
#include "./PolyDiM/gedim/GeDiM/src/Geometry/MapQuadrilateral.hpp"
#include "./PolyDiM/gedim/GeDiM/src/Geometry/MapParallelogram.hpp"
#include "./PolyDiM/gedim/GeDiM/src/Geometry/MapHexahedron.hpp"
#include "./PolyDiM/gedim/GeDiM/src/Geometry/GeometryUtilities.hpp"
#include "./PolyDiM/gedim/GeDiM/src/Geometry/MapParallelepiped.hpp"
#include "./PolyDiM/gedim/GeDiM/src/Geometry/MapTriangle.hpp"

// #include "./PolyDiM/gedim/GeDiM/src/Algebra/PETSc_KSPSolver.hpp"
// #include "./PolyDiM/gedim/GeDiM/src/Algebra/Eigen_Array.hpp"
// #include "./PolyDiM/gedim/GeDiM/src/Algebra/Eigen_PCGSolver.hpp"
// #include "./PolyDiM/gedim/GeDiM/src/Algebra/Eigen_LUSolver.hpp"
// #include "./PolyDiM/gedim/GeDiM/src/Algebra/IArray.hpp"
// #include "./PolyDiM/gedim/GeDiM/src/Algebra/PETSc_Array.hpp"
// #include "./PolyDiM/gedim/GeDiM/src/Algebra/LAPACK_utilities.hpp"
// #include "./PolyDiM/gedim/GeDiM/src/Algebra/Eigen_CholeskySolver.hpp"
// #include "./PolyDiM/gedim/GeDiM/src/Algebra/Eigen_BiCGSTABSolver.hpp"
// #include "./PolyDiM/gedim/GeDiM/src/Algebra/Pardiso_LUSolver.hpp"
// #include "./PolyDiM/gedim/GeDiM/src/Algebra/SuiteSparse_Utilities.hpp"
// #include "./PolyDiM/gedim/GeDiM/src/Algebra/PETSc_SparseArray.hpp"
// #include "./PolyDiM/gedim/GeDiM/src/Algebra/ISparseArray.hpp"
// #include "./PolyDiM/gedim/GeDiM/src/Algebra/ILinearSolver.hpp"
// #include "./PolyDiM/gedim/GeDiM/src/Algebra/Eigen_SparseArray.hpp"
// #include "./PolyDiM/gedim/GeDiM/src/Algebra/Pardiso_CholeskySolver.hpp"
// #include "./PolyDiM/gedim/GeDiM/src/Algebra/Eigen_Utilities.hpp"

#include "./PolyDiM/PolyDiM/src/Interpolation/lagrange_1D.hpp"

#include "./PolyDiM/PolyDiM/src/VEM/Quadrature/VEM_Quadrature_2D.hpp"
#include "./PolyDiM/PolyDiM/src/VEM/Quadrature/VEM_Quadrature_3D.hpp"

#include "./PolyDiM/PolyDiM/src/Utilities/GBasis_2D.hpp"
#include "./PolyDiM/PolyDiM/src/Utilities/GBasis_3D.hpp"
#include "./PolyDiM/PolyDiM/src/Utilities/GBasis_Data.hpp"
#include "./PolyDiM/PolyDiM/src/Utilities/Monomials_1D.hpp"
#include "./PolyDiM/PolyDiM/src/Utilities/Monomials_2D.hpp"
#include "./PolyDiM/PolyDiM/src/Utilities/Monomials_3D.hpp"
#include "./PolyDiM/PolyDiM/src/Utilities/Monomials_Data.hpp"
#include "./PolyDiM/PolyDiM/src/Utilities/Monomials_Utilities.hpp"
#include "./PolyDiM/PolyDiM/src/Utilities/Inertia_Utilities.hpp"

#include "./PolyDiM/PolyDiM/src/VEM/PCC/VEM_PCC_Utilities.hpp"

#include "./PolyDiM/PolyDiM/src/VEM/PCC/2D/VEM_PCC_2D_Creator.hpp"
#include "./PolyDiM/PolyDiM/src/VEM/PCC/2D/VEM_PCC_2D_LocalSpace.hpp"
#include "./PolyDiM/PolyDiM/src/VEM/PCC/2D/VEM_PCC_2D_Inertia_LocalSpace.hpp"
#include "./PolyDiM/PolyDiM/src/VEM/PCC/2D/VEM_PCC_2D_Ortho_LocalSpace.hpp"
#include "./PolyDiM/PolyDiM/src/VEM/PCC/2D/VEM_PCC_2D_ReferenceElement.hpp"
#include "./PolyDiM/PolyDiM/src/VEM/PCC/2D/VEM_PCC_2D_LocalSpace_Data.hpp"

#include "./PolyDiM/PolyDiM/src/VEM/PCC/3D/VEM_PCC_3D_Creator.hpp"
#include "./PolyDiM/PolyDiM/src/VEM/PCC/3D/VEM_PCC_3D_LocalSpace.hpp"
#include "./PolyDiM/PolyDiM/src/VEM/PCC/3D/VEM_PCC_3D_Inertia_LocalSpace.hpp"
#include "./PolyDiM/PolyDiM/src/VEM/PCC/3D/VEM_PCC_3D_Ortho_LocalSpace.hpp"
#include "./PolyDiM/PolyDiM/src/VEM/PCC/3D/VEM_PCC_3D_ReferenceElement.hpp"
#include "./PolyDiM/PolyDiM/src/VEM/PCC/3D/VEM_PCC_3D_LocalSpace_Data.hpp"

#include "./PolyDiM/PolyDiM/src/VEM/MCC/VEM_MCC_Utilities.hpp"

#include "./PolyDiM/PolyDiM/src/VEM/MCC/2D/VEM_MCC_2D_Creator.hpp"
#include "./PolyDiM/PolyDiM/src/VEM/MCC/2D/VEM_MCC_2D_EdgeOrtho_ReferenceElement.hpp"
#include "./PolyDiM/PolyDiM/src/VEM/MCC/2D/VEM_MCC_2D_EdgeOrtho_Velocity_LocalSpace.hpp"
#include "./PolyDiM/PolyDiM/src/VEM/MCC/2D/VEM_MCC_2D_LocalSpace_Data.hpp"
#include "./PolyDiM/PolyDiM/src/VEM/MCC/2D/VEM_MCC_2D_Ortho_EdgeOrtho_Velocity_LocalSpace.hpp"
#include "./PolyDiM/PolyDiM/src/VEM/MCC/2D/VEM_MCC_2D_Ortho_Velocity_LocalSpace.hpp"
#include "./PolyDiM/PolyDiM/src/VEM/MCC/2D/VEM_MCC_2D_Partial_Velocity_LocalSpace.hpp"
#include "./PolyDiM/PolyDiM/src/VEM/MCC/2D/VEM_MCC_2D_Pressure_LocalSpace.hpp"
#include "./PolyDiM/PolyDiM/src/VEM/MCC/2D/VEM_MCC_2D_ReferenceElement.hpp"
#include "./PolyDiM/PolyDiM/src/VEM/MCC/2D/VEM_MCC_2D_Velocity_LocalSpace.hpp"

#include "./PolyDiM/PolyDiM/src/VEM/MCC/3D/VEM_MCC_3D_Creator.hpp"
#include "./PolyDiM/PolyDiM/src/VEM/MCC/3D/VEM_MCC_3D_LocalSpace_Data.hpp"
#include "./PolyDiM/PolyDiM/src/VEM/MCC/3D/VEM_MCC_3D_Pressure_LocalSpace.hpp"
#include "./PolyDiM/PolyDiM/src/VEM/MCC/3D/VEM_MCC_3D_ReferenceElement.hpp"
#include "./PolyDiM/PolyDiM/src/VEM/MCC/3D/VEM_MCC_3D_Velocity_LocalSpace.hpp"

#include "./PolyDiM/PolyDiM/src/VEM/DF_PCC/VEM_DF_PCC_Utilities.hpp"

#include "./PolyDiM/PolyDiM/src/VEM/DF_PCC/2D/VEM_DF_PCC_2D_Creator.hpp"
#include "./PolyDiM/PolyDiM/src/VEM/DF_PCC/2D/VEM_DF_PCC_2D_LocalSpace_Data.hpp"
#include "./PolyDiM/PolyDiM/src/VEM/DF_PCC/2D/VEM_DF_PCC_2D_Pressure_LocalSpace.hpp"
#include "./PolyDiM/PolyDiM/src/VEM/DF_PCC/2D/VEM_DF_PCC_2D_Reduced_Pressure_LocalSpace.hpp"
#include "./PolyDiM/PolyDiM/src/VEM/DF_PCC/2D/VEM_DF_PCC_2D_Reduced_ReferenceElement.hpp"
#include "./PolyDiM/PolyDiM/src/VEM/DF_PCC/2D/VEM_DF_PCC_2D_Reduced_Velocity_LocalSpace.hpp"
#include "./PolyDiM/PolyDiM/src/VEM/DF_PCC/2D/VEM_DF_PCC_2D_ReferenceElement.hpp"
#include "./PolyDiM/PolyDiM/src/VEM/DF_PCC/2D/VEM_DF_PCC_2D_Velocity_LocalSpace.hpp"

#include "./PolyDiM/PolyDiM/src/VEM/DF_PCC/3D/VEM_DF_PCC_3D_Creator.hpp"
#include "./PolyDiM/PolyDiM/src/VEM/DF_PCC/3D/VEM_DF_PCC_3D_LocalSpace_Data.hpp"
#include "./PolyDiM/PolyDiM/src/VEM/DF_PCC/3D/VEM_DF_PCC_3D_Pressure_LocalSpace.hpp"
#include "./PolyDiM/PolyDiM/src/VEM/DF_PCC/3D/VEM_DF_PCC_3D_Reduced_Pressure_LocalSpace.hpp"
#include "./PolyDiM/PolyDiM/src/VEM/DF_PCC/3D/VEM_DF_PCC_3D_Reduced_ReferenceElement.hpp"
#include "./PolyDiM/PolyDiM/src/VEM/DF_PCC/3D/VEM_DF_PCC_3D_Reduced_Velocity_LocalSpace.hpp"
#include "./PolyDiM/PolyDiM/src/VEM/DF_PCC/3D/VEM_DF_PCC_3D_ReferenceElement.hpp"
#include "./PolyDiM/PolyDiM/src/VEM/DF_PCC/3D/VEM_DF_PCC_3D_Velocity_LocalSpace.hpp"

#include "./PolyDiM/PolyDiM/src/FEM/PCC/1D/FEM_PCC_1D_LocalSpace.hpp"
#include "./PolyDiM/PolyDiM/src/FEM/PCC/1D/FEM_PCC_1D_ReferenceElement.hpp"

#include "./PolyDiM/PolyDiM/src/FEM/PCC/2D/FEM_PCC_2D_LocalSpace_Data.hpp"
#include "./PolyDiM/PolyDiM/src/FEM/PCC/2D/FEM_PCC_2D_LocalSpace.hpp"
#include "./PolyDiM/PolyDiM/src/FEM/PCC/2D/FEM_PCC_2D_ReferenceElement.hpp"
#include "./PolyDiM/PolyDiM/src/FEM/PCC/2D/FEM_Quadrilateral_PCC_2D_LocalSpace.hpp"
#include "./PolyDiM/PolyDiM/src/FEM/PCC/2D/FEM_Quadrilateral_PCC_2D_ReferenceElement.hpp"
#include "./PolyDiM/PolyDiM/src/FEM/PCC/2D/FEM_Triangle_PCC_2D_ReferenceElement.hpp"
#include "./PolyDiM/PolyDiM/src/FEM/PCC/2D/FEM_Triangle_PCC_2D_LocalSpace.hpp"

#include "./PolyDiM/PolyDiM/src/FEM/PCC/3D/FEM_PCC_3D_LocalSpace_Data.hpp"
#include "./PolyDiM/PolyDiM/src/FEM/PCC/3D/FEM_PCC_3D_LocalSpace.hpp"
#include "./PolyDiM/PolyDiM/src/FEM/PCC/3D/FEM_PCC_3D_ReferenceElement.hpp"
#include "./PolyDiM/PolyDiM/src/FEM/PCC/3D/FEM_Hexahedron_PCC_3D_LocalSpace.hpp"
#include "./PolyDiM/PolyDiM/src/FEM/PCC/3D/FEM_Hexahedron_PCC_3D_ReferenceElement.hpp"
#include "./PolyDiM/PolyDiM/src/FEM/PCC/3D/FEM_Tetrahedron_PCC_3D_LocalSpace.hpp"
#include "./PolyDiM/PolyDiM/src/FEM/PCC/3D/FEM_Tetrahedron_PCC_3D_ReferenceElement.hpp"

#include "./PolyDiM/PolyDiM/src/FEM/PCC/3D/FEM_PCC_3D_LocalSpace_Data.hpp"
#include "./PolyDiM/PolyDiM/src/FEM/PCC/3D/FEM_PCC_3D_LocalSpace.hpp"
#include "./PolyDiM/PolyDiM/src/FEM/PCC/3D/FEM_PCC_3D_ReferenceElement.hpp"
#include "./PolyDiM/PolyDiM/src/FEM/PCC/3D/FEM_Hexahedron_PCC_3D_LocalSpace.hpp"
#include "./PolyDiM/PolyDiM/src/FEM/PCC/3D/FEM_Hexahedron_PCC_3D_ReferenceElement.hpp"
#include "./PolyDiM/PolyDiM/src/FEM/PCC/3D/FEM_Tetrahedron_PCC_3D_LocalSpace.hpp"
#include "./PolyDiM/PolyDiM/src/FEM/PCC/3D/FEM_Tetrahedron_PCC_3D_ReferenceElement.hpp"

#include "./PolyDiM/PolyDiM/src/FEM/MCC/2D/FEM_Triangle_RT_MCC_2D_ReferenceElement.hpp",
#include "./PolyDiM/PolyDiM/src/FEM/MCC/2D/FEM_Triangle_RT_MCC_2D_LocalSpace.hpp",
#include "./PolyDiM/PolyDiM/src/FEM/MCC/2D/FEM_MCC_2D_ReferenceElement.hpp",
#include "./PolyDiM/PolyDiM/src/FEM/MCC/2D/FEM_MCC_2D_LocalSpace_Data.hpp",
#include "./PolyDiM/PolyDiM/src/FEM/MCC/2D/FEM_MCC_2D_LocalSpace.hpp",

#include "./PolyDiM/PolyDiM/src/PDETools/Assembler/Assembler_Utilities.hpp"
#include "./PolyDiM/PolyDiM/src/PDETools/DOFs/DOFsManager.hpp"
#include "./PolyDiM/PolyDiM/src/PDETools/Equations/EllipticEquation.hpp"
#include "./PolyDiM/PolyDiM/src/PDETools/Mesh/MeshMatricesDAO_mesh_connectivity_data.hpp"
#include "./PolyDiM/PolyDiM/src/PDETools/Mesh/PDE_Mesh_Utilities.hpp"

#include "./PolyDiM/PolyDiM/src/PDETools/LocalSpace/LocalSpace_PCC_2D.hpp"
#include "./PolyDiM/PolyDiM/src/PDETools/LocalSpace/LocalSpace_PCC_3D.hpp"
#include "./PolyDiM/PolyDiM/src/PDETools/LocalSpace/LocalSpace_MCC_2D.hpp"