import litgen

opts = litgen.LitgenOptions()
# opts.python_expose_enum_class = True
# opts.classes_expose_nested = True
# opts.enum_remove_scope = False
# opts.class_remove_scope = False


opts.srcmlcpp_options.header_filter_preprocessor_regions = True

opts.fn_template_options.add_specialization("Parse", ["std::vector<unsigned int>", "std::vector<double>", "std::set<unsigned int>", "std::vector<int>", "bool", "std::string", "double", "float", "char", "int"], add_suffix_to_function_name=True)

opts.type_replacements.add_replacement("Gedim::IMeshDAO", "Gedim::MeshMatricesDAO")

# opts.fn_template_options.add_specialization("Timer", ["std::chrono::milliseconds"], add_suffix_to_function_name=True)

headers = ["PolyDiM/gedim/GeDiM/src/IO/StringsUtilities.hpp",
           "PolyDiM/gedim/GeDiM/src/Geometry/GeometryUtilities.hpp",
           "PolyDiM/gedim/GeDiM/src/Geometry/MapParallelepiped.hpp",
           "PolyDiM/gedim/GeDiM/src/Geometry/MapHexahedron.hpp",
           "PolyDiM/gedim/GeDiM/src/Geometry/MapTriangle.hpp",
           "PolyDiM/gedim/GeDiM/src/Geometry/MapParallelogram.hpp",
           "PolyDiM/gedim/GeDiM/src/Geometry/MapTetrahedron.hpp",
           "PolyDiM/gedim/GeDiM/src/Geometry/MapQuadrilateral.hpp",
            #"PolyDiM/gedim/GeDiM/src/Mesh/ConformerMeshPolygon.hpp",
            #"PolyDiM/gedim/GeDiM/src/Mesh/ConformerMeshSegment.hpp",
            #"PolyDiM/gedim/GeDiM/src/Mesh/ConformMeshUtilities.hpp",
            #"PolyDiM/gedim/GeDiM/src/Mesh/IntersectorMesh2DSegment.hpp",
            #"PolyDiM/gedim/GeDiM/src/Mesh/IntersectorMesh3DSegment.hpp",
            "PolyDiM/gedim/GeDiM/src/Mesh/MeshDAOExporterToCsv.hpp",
            "PolyDiM/gedim/GeDiM/src/Mesh/MeshDAOImporterFromCsv.hpp",
            "PolyDiM/gedim/GeDiM/src/Mesh/MeshFromCsvUtilities.hpp",
            "PolyDiM/gedim/GeDiM/src/Mesh/MeshMatrices.hpp",
            "PolyDiM/gedim/GeDiM/src/Mesh/MeshMatricesDAO.hpp",
            "PolyDiM/gedim/GeDiM/src/Mesh/MeshUtilities.hpp",
            #"PolyDiM/gedim/GeDiM/src/Mesh/ObjectFileFormatInterface.hpp",
            #"PolyDiM/gedim/GeDiM/src/Mesh/OpenVolumeMeshInterface.hpp",
            "PolyDiM/gedim/GeDiM/src/Mesh/PlatonicSolid.hpp",
            #"PolyDiM/gedim/GeDiM/src/Mesh/RefinementUtilities.hpp",
            "PolyDiM/gedim/GeDiM/src/Mesh/SphereMeshUtilities.hpp",
            #"PolyDiM/gedim/GeDiM/src/Mesh/TetgenInterface.hpp",
            #"PolyDiM/gedim/GeDiM/src/Mesh/TriangleInterface.hpp",
            #"PolyDiM/gedim/GeDiM/src/Mesh/UnionMeshSegment.hpp",
            #"PolyDiM/gedim/GeDiM/src/Mesh/VoroInterface.hpp",
            #"PolyDiM/gedim/GeDiM/src/Mesh/VtkMeshInterface.hpp",
            "PolyDiM/gedim/GeDiM/src/Quadrature/Quadrature_Gauss2D_Triangle.hpp",
            "PolyDiM/gedim/GeDiM/src/Quadrature/Quadrature_Gauss2D_Square.hpp",
            "PolyDiM/gedim/GeDiM/src/Quadrature/Quadrature_Gauss3D_Hexahedron.hpp",
            "PolyDiM/gedim/GeDiM/src/Quadrature/Quadrature_GaussLobatto1D.hpp",
            "PolyDiM/gedim/GeDiM/src/Quadrature/Quadrature_Gauss1D.hpp",
            "PolyDiM/gedim/GeDiM/src/Quadrature/QuadratureData.hpp",
            "PolyDiM/gedim/GeDiM/src/Quadrature/Quadrature_Gauss3D_Tetrahedron_PositiveWeights.hpp",
            "PolyDiM/gedim/GeDiM/src/Quadrature/Quadrature_Gauss3D_Tetrahedron.hpp",
            "PolyDiM/PolyDiM/src/Interpolation/lagrange_1D.hpp",
            "PolyDiM/PolyDiM/src/VEM/Quadrature/VEM_Quadrature_2D.hpp",
            "PolyDiM/PolyDiM/src/VEM/Quadrature/VEM_Quadrature_3D.hpp",
            "PolyDiM/PolyDiM/src/Utilities/Monomials_Data.hpp",
            "PolyDiM/PolyDiM/src/Utilities/GBasis_Data.hpp",
            "PolyDiM/PolyDiM/src/Utilities/GBasis_2D.hpp",
            "PolyDiM/PolyDiM/src/Utilities/GBasis_3D.hpp",
            #"PolyDiM/PolyDiM/src/Utilities/Monomials_Utilities.hpp",
            "PolyDiM/PolyDiM/src/Utilities/Monomials_1D.hpp",
            "PolyDiM/PolyDiM/src/Utilities/Monomials_2D.hpp",
            "PolyDiM/PolyDiM/src/Utilities/Monomials_3D.hpp",
            "PolyDiM/PolyDiM/src/Utilities/Inertia_Utilities.hpp",
            "PolyDiM/PolyDiM/src/VEM/PCC/2D/VEM_PCC_2D_ReferenceElement.hpp",
            "PolyDiM/PolyDiM/src/VEM/PCC/2D/VEM_PCC_2D_LocalSpace_Data.hpp",
            "PolyDiM/PolyDiM/src/VEM/PCC/3D/VEM_PCC_3D_ReferenceElement.hpp",
            "PolyDiM/PolyDiM/src/VEM/MCC/3D/VEM_MCC_3D_LocalSpace_Data.hpp",
            "PolyDiM/PolyDiM/src/VEM/MCC/2D/VEM_MCC_2D_EdgeOrtho_ReferenceElement.hpp",
            "PolyDiM/PolyDiM/src/VEM/PCC/2D/VEM_PCC_2D_Creator.hpp",
            "PolyDiM/PolyDiM/src/VEM/PCC/2D/VEM_PCC_2D_LocalSpace.hpp",
            "PolyDiM/PolyDiM/src/VEM/PCC/2D/VEM_PCC_2D_Inertia_LocalSpace.hpp",
            "PolyDiM/PolyDiM/src/VEM/PCC/2D/VEM_PCC_2D_Ortho_LocalSpace.hpp",
            "PolyDiM/PolyDiM/src/VEM/PCC/3D/VEM_PCC_3D_Creator.hpp",
            "PolyDiM/PolyDiM/src/VEM/PCC/3D/VEM_PCC_3D_LocalSpace.hpp",
            "PolyDiM/PolyDiM/src/VEM/PCC/3D/VEM_PCC_3D_Inertia_LocalSpace.hpp",
            "PolyDiM/PolyDiM/src/VEM/PCC/3D/VEM_PCC_3D_Ortho_LocalSpace.hpp",
            "PolyDiM/PolyDiM/src/VEM/PCC/3D/VEM_PCC_3D_LocalSpace_Data.hpp",
            "PolyDiM/PolyDiM/src/VEM/MCC/2D/VEM_MCC_2D_Creator.hpp",
            "PolyDiM/PolyDiM/src/VEM/MCC/2D/VEM_MCC_2D_EdgeOrtho_Velocity_LocalSpace.hpp",
            "PolyDiM/PolyDiM/src/VEM/MCC/2D/VEM_MCC_2D_LocalSpace_Data.hpp",
            "PolyDiM/PolyDiM/src/VEM/MCC/2D/VEM_MCC_2D_Ortho_EdgeOrtho_Velocity_LocalSpace.hpp",
            "PolyDiM/PolyDiM/src/VEM/MCC/2D/VEM_MCC_2D_Ortho_Velocity_LocalSpace.hpp",
            "PolyDiM/PolyDiM/src/VEM/MCC/2D/VEM_MCC_2D_Partial_Velocity_LocalSpace.hpp",
            "PolyDiM/PolyDiM/src/VEM/MCC/2D/VEM_MCC_2D_Pressure_LocalSpace.hpp",
            "PolyDiM/PolyDiM/src/VEM/MCC/2D/VEM_MCC_2D_ReferenceElement.hpp",
            "PolyDiM/PolyDiM/src/VEM/MCC/2D/VEM_MCC_2D_Velocity_LocalSpace.hpp",
            "PolyDiM/PolyDiM/src/VEM/MCC/3D/VEM_MCC_3D_Creator.hpp",
            "PolyDiM/PolyDiM/src/VEM/MCC/3D/VEM_MCC_3D_Pressure_LocalSpace.hpp",
            "PolyDiM/PolyDiM/src/VEM/MCC/3D/VEM_MCC_3D_ReferenceElement.hpp",
            "PolyDiM/PolyDiM/src/VEM/MCC/3D/VEM_MCC_3D_Velocity_LocalSpace.hpp",
            "PolyDiM/PolyDiM/src/VEM/DF_PCC/2D/VEM_DF_PCC_2D_Creator.hpp",
            "PolyDiM/PolyDiM/src/VEM/DF_PCC/2D/VEM_DF_PCC_2D_LocalSpace_Data.hpp",
            "PolyDiM/PolyDiM/src/VEM/DF_PCC/2D/VEM_DF_PCC_2D_Pressure_LocalSpace.hpp",
            "PolyDiM/PolyDiM/src/VEM/DF_PCC/2D/VEM_DF_PCC_2D_Reduced_Pressure_LocalSpace.hpp",
            "PolyDiM/PolyDiM/src/VEM/DF_PCC/2D/VEM_DF_PCC_2D_Reduced_ReferenceElement.hpp",
            "PolyDiM/PolyDiM/src/VEM/DF_PCC/2D/VEM_DF_PCC_2D_Reduced_Velocity_LocalSpace.hpp",
            "PolyDiM/PolyDiM/src/VEM/DF_PCC/2D/VEM_DF_PCC_2D_ReferenceElement.hpp",
            "PolyDiM/PolyDiM/src/VEM/DF_PCC/2D/VEM_DF_PCC_2D_Velocity_LocalSpace.hpp",
            "PolyDiM/PolyDiM/src/VEM/DF_PCC/3D/VEM_DF_PCC_3D_Creator.hpp",
            "PolyDiM/PolyDiM/src/VEM/DF_PCC/3D/VEM_DF_PCC_3D_LocalSpace_Data.hpp",
            "PolyDiM/PolyDiM/src/VEM/DF_PCC/3D/VEM_DF_PCC_3D_Pressure_LocalSpace.hpp",
            "PolyDiM/PolyDiM/src/VEM/DF_PCC/3D/VEM_DF_PCC_3D_Reduced_Pressure_LocalSpace.hpp",
            "PolyDiM/PolyDiM/src/VEM/DF_PCC/3D/VEM_DF_PCC_3D_Reduced_ReferenceElement.hpp",
            "PolyDiM/PolyDiM/src/VEM/DF_PCC/3D/VEM_DF_PCC_3D_Reduced_Velocity_LocalSpace.hpp",
            "PolyDiM/PolyDiM/src/VEM/DF_PCC/3D/VEM_DF_PCC_3D_ReferenceElement.hpp",
            "PolyDiM/PolyDiM/src/VEM/DF_PCC/3D/VEM_DF_PCC_3D_Velocity_LocalSpace.hpp",
            #"PolyDiM/PolyDiM/src/PDETools/Assembler/Assembler_Utilities.hpp",
            #"PolyDiM/PolyDiM/src/PDETools/DOFs/DOFsManager.hpp",
            #"PolyDiM/PolyDiM/src/PDETools/Mesh/PDE_Mesh_Utilities.hpp",
            #"PolyDiM/PolyDiM/src/PDETools/Equations/EllipticEquation.hpp",
            #"PolyDiM/PolyDiM/src/PDETools/Mesh/MeshMatricesDAO_mesh_connectivity_data.hpp",
            "PolyDiM/PolyDiM/src/FEM/PCC/1D/FEM_PCC_1D_LocalSpace.hpp",
            "PolyDiM/PolyDiM/src/FEM/PCC/1D/FEM_PCC_1D_ReferenceElement.hpp",
            "PolyDiM/PolyDiM/src/FEM/PCC/2D/FEM_PCC_2D_LocalSpace_Data.hpp",
            "PolyDiM/PolyDiM/src/FEM/PCC/2D/FEM_Quadrilateral_PCC_2D_LocalSpace.hpp",
            "PolyDiM/PolyDiM/src/FEM/PCC/2D/FEM_Quadrilateral_PCC_2D_ReferenceElement.hpp",
            "PolyDiM/PolyDiM/src/FEM/PCC/2D/FEM_Triangle_PCC_2D_ReferenceElement.hpp",
            "PolyDiM/PolyDiM/src/FEM/PCC/2D/FEM_Triangle_PCC_2D_LocalSpace.hpp",
            "PolyDiM/PolyDiM/src/FEM/PCC/2D/FEM_PCC_2D_ReferenceElement.hpp",
            "PolyDiM/PolyDiM/src/FEM/PCC/2D/FEM_PCC_2D_LocalSpace.hpp",
            "PolyDiM/PolyDiM/src/FEM/PCC/3D/FEM_Hexahedron_PCC_3D_ReferenceElement.hpp",
            "PolyDiM/PolyDiM/src/FEM/PCC/3D/FEM_Hexahedron_PCC_3D_LocalSpace.hpp",
            "PolyDiM/PolyDiM/src/FEM/PCC/3D/FEM_Tetrahedron_PCC_3D_ReferenceElement.hpp",
            "PolyDiM/PolyDiM/src/FEM/PCC/3D/FEM_Tetrahedron_PCC_3D_LocalSpace.hpp",
            "PolyDiM/PolyDiM/src/FEM/PCC/3D/FEM_PCC_3D_ReferenceElement.hpp",
            "PolyDiM/PolyDiM/src/FEM/PCC/3D/FEM_PCC_3D_LocalSpace_Data.hpp",
            "PolyDiM/PolyDiM/src/FEM/PCC/3D/FEM_PCC_3D_LocalSpace.hpp",
            ]

# Stampa a console:
litgen.write_generated_code_for_files(
    options=opts,
    input_cpp_header_files=headers,
    output_cpp_pydef_file="bindings.cpp",
    output_stub_pyi_file="pypolydim.pyi",
)