name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ubuntu-latest #${{ matrix.os }}
    runs-on: ubuntu-latest #${{ matrix.os }}
    #strategy:
    #  matrix:
        # macos-15-intel is an Intel runner, macos-14 is Apple silicon
    #    os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-11-arm, macos-15-intel, macos-14]

    steps:
      - uses: actions/checkout@v5

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.2.0
        # env:
        #   CIBW_SOME_OPTION: value
        #   ...
        with:
        #   package-dir: .
          output-dir: wheelhouse
        #   config-file: "{package}/pyproject.toml"
      
      - name: Upload to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          pip install twine
          twine upload --repository-url https://test.pypi.org/legacy/ wheelhouse/*
